language: go

sudo: false

go:
  - "1.9"
  - "1.10"

install:
  - source .default.env
  - go get ./...
  - go get github.com/golang/lint/golint
  - go get github.com/kisielk/errcheck

stages:
  - verification
  - test

jobs:
  include:
    - stage: verification
      script: make verification

    - stage: test
      script: make test
