SHELL:=/bin/bash

test:
	go test -covermode=count -coverprofile=./profile.coverprofile -parallel 5 -tags='unit integration' -v ./...

unit:
	go test -tags=unit ./...

integration:
	go test -parallel 5 -tags=integration ./...

verification:
	go vet ./...
	golint -set_exit_status ./...
	CGO_ENABLED=0 errcheck ./...
